name: Build and Push Docker Image with Kaniko

on:
  push:
    tags:
      - '*'  # Se déclenche seulement quand un tag est poussé, comme dans votre GitLab CI

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    container:
      image: gcr.io/kaniko-project/executor:v1.23.2-debug
      options: --entrypoint=""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Docker config
        # Création du fichier de configuration pour l'authentification à GHCR
        run: |
          mkdir -p /kaniko/.docker
          echo '{"auths":{"ghcr.io":{"username":"${{ github.repository_owner }}","password":"${{ secrets.GITHUB_TOKEN }}"}}}' > /kaniko/.docker/config.json

      - name: Build and push with Kaniko
        # Commande équivalente à celle de votre GitLab CI
        run: |
          /kaniko/executor \
            --context "${{ github.workspace }}" \
            --dockerfile "${{ github.workspace }}/Dockerfile" \
            --destination "ghcr.io/${{ github.repository }}:${{ github.ref_name }}" \
            --destination "ghcr.io/${{ github.repository }}:latest"
