name: Build and Push Docker Image with Kaniko

on:
  push:
    branches:
      - '*'  # Se déclenche à chaque push sur n'importe quelle branche
    tags:
      - '*'  # Se déclenche aussi avec les tags

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    container:
      image: gcr.io/kaniko-project/executor:v1.23.2-debug
      options: --entrypoint=""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Docker config
        # Création du fichier de configuration pour l'authentification à GHCR
        run: |
          mkdir -p /kaniko/.docker
          echo '{"auths":{"ghcr.io":{"username":"${{ github.repository_owner }}","password":"${{ secrets.GITHUB_TOKEN }}"}}}' > /kaniko/.docker/config.json

      - name: Build and push with Kaniko
        # Commande équivalente à celle de votre GitLab CI
        run: |
          # Définir le tag en fonction du type de référence (branche ou tag)
          TAG_NAME=""
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG_NAME="${{ github.ref_name }}"
          else
            # Pour les branches, on utilise le nom de la branche
            TAG_NAME="${{ github.ref_name }}"
          fi
          
          /kaniko/executor \
            --context "${{ github.workspace }}" \
            --dockerfile "${{ github.workspace }}/Dockerfile" \
            --destination "ghcr.io/${{ github.repository }}:${TAG_NAME}" \
            --destination "ghcr.io/${{ github.repository }}:latest"
